# Generated by Django 4.1.9 on 2023-09-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
