# Generated by Django 4.1.9 on 2023-09-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
