# Generated by Django 4.1.9 on 2023-09-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievances',
            name='priority',
            field=models.CharField(default='NOR', max_length=3),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='stage',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.CharField(default='usr', max_length=3),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(default='AVA', max_length=3),
        ),
    ]
