# Generated by Django 4.1.9 on 2023-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_grievances_priority_alter_grievances_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='aadhar',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='worker',
            name='dept',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='dept',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
