# Generated by Django 4.1.9 on 2023-09-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_worker_aadhar_worker_dept_worker_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
