# Generated by Django 4.1.9 on 2023-09-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievances',
            name='wid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_grievances', to='api.worker'),
        ),
    ]
