# Generated by Django 4.1.9 on 2023-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_grievances_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievances',
            name='usr_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/user'),
        ),
        migrations.AlterField(
            model_name='grievances',
            name='wrk_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/worker'),
        ),
    ]
